### ISSUE TITLE
Support V1 Syntax in V2

### ISSUE THREAD

**Issue by sylvainbaronnet** [jonathantneal/postcss-short-font-size#1]
Hi,

While I appreciate the new syntax possibility (`!important`) I also like the simplicity of the previous version (whithout `/`)

I think it would not be very difficult to continue to support the V1 syntax in V2 (detect `/` ?)

It's also nice to be able to use it in older project.

(Maybe only with an opt-in option, like `compatibilty_v1:true`)

**Comment by jonathantneal** [comment]
I had wanted to make the dividing character an option, but then imagine the following selectors:

``` css
.a {
  font-size: 16px !important 2;
}
.b {
  font-size: 16px 2 !important;
}
.c {
  font-size: 16px !important 2 !important;
}
```

This would require a second set of expectations in the plugin when the character is a spacer. I’ll spend some time looking at what this would take. A PR would be gladly reviewed.
